### ISSUE TITLE
How to remove a voiceprint?

### ISSUE THREAD

**Issue by roccolocko** [amaurycrickx/recognito#22]
Hello @amaurycrickx ,
     I see that you have a merge function, but what should I do if I want to remove a key+print from the store. The store is private (as it should be) but there is no set/get to do a .remove(key).
     Is there a way to do this that I have missed?

Thank you!
--
Roberto

**Comment by Krishansharma** [comment]
File not supported error when i  use .wav file
*********************************************************************************************
javax.sound.sampled.UnsupportedAudioFileException: format not supported
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at javax.sound.sampled.AudioSystem.getAudioInputStreamImpl(AudioSystem.java:1023)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1005)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at com.bitsinharmony.recognito.Recognito.convertFileToDoubleArray(Recognito.java:226)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at com.bitsinharmony.recognito.Recognito.createVoicePrint(Recognito.java:211)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at com.speechreco.MainActivity$1$1.OnClickListener(MainActivity.java:54)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at com.deskode.recorddialog.RecordDialog$2.onClick(RecordDialog.java:142)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at android.os.Looper.loop(Looper.java:158)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7225)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
03-20 19:32:08.243 3536-3536/com.speechreco W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by channae** [comment]
Were you able to figure out a solution to remove the voice print? I'm having the same requirement.

**Comment by stefan-reich** [comment]
There is no way with the library as it is. Really simple to add though, just make a 1-line `deleteVoicePrint` method. You can make a subclass of `Recognito` for this if you don't want to change the original library.
